In [26]:
from numpy import linalg 
import numpy as np

In [4]:
L=[1,2,3,4,3,5]
arr1=np.array(L)
arr1

array([1, 2, 3, 4, 3, 5])

In [12]:
LN=[[1,2,3],[2,2,12]]
arr2=np.array(LN)
arr2

array([[ 1,  2,  3],
       [ 2,  2, 12]])

In [15]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [9]:
arr2.shape

(2, 3)

In [10]:
arr1.shape

(6,)

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])