Tensors are the data structure used by machine learning systems, and getting to know them is an essential skill you should build early on. A tensor is a container for numerical data. It is the way we store the information that we'll use within our system.

0d

In [63]:
import numpy as np

In [64]:
a = np.array(2)

In [65]:
a

array(2)

In [66]:
a.ndim

0

1d

In [67]:
arr = np.array([1,2,3,4,5])

In [68]:
arr

array([1, 2, 3, 4, 5])

In [69]:
arr.ndim

1

2d

In [70]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
mat.ndim

2

3d

In [73]:
collection_mat = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [74]:
collection_mat

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [75]:
collection_mat.ndim

3

sclaer --> vector --> matrix --> cube