#### simple example with two inputs and one output and logic AND

In [38]:
from numpy import exp, array, random, dot

In [39]:
#parameters
inputs = array([[0,0],[0,1],[1,0],[1,1]])
outputs = array([[0,1,1,1]]).T

In [40]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [41]:
outputs

array([[0],
       [1],
       [1],
       [1]])

In [42]:
random.seed(1)

In [43]:
weights = 2 * random.random((2,1)) - 1
weights

array([[-0.16595599],
       [ 0.44064899]])

In [44]:
# single neuron
def neuron(inputs,weights):
    output = 1 /  (1 + exp(-(dot(inputs,weights))))
    return output

In [45]:
#train
for iteration in range(500000):
    output = 1 / (1 + exp(-(dot(inputs,weights))))
    weights += dot(inputs.T, (outputs - output) * output * (1 - output))

In [46]:
#test 
x = array([1,0])
print(neuron(x,weights))

[0.998998]


#### MLP using sklearn

In [47]:
from sklearn.neural_network import MLPClassifier

In [48]:
X = [[0.,0.],[0.,1.],[1.,0.],[1.,1.]]
y = [0,1,1,1]

In [49]:
clf = MLPClassifier(solver="lbfgs", alpha=1e-5, hidden_layer_sizes=(5,2), random_state=1)
clf.fit(X,y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [50]:
print(clf.predict([[2.,2.],[-1.,-2.]]))
print([coef.shape for coef in clf.coefs_])

[1 0]
[(2, 5), (5, 2), (2, 1)]


#### A simple Keras multiple layer perceptron for the Breast Cancer Classification

In [95]:
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras import optimizers
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
data = load_breast_cancer()

In [96]:
X = data.data
y = data.target

In [97]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [98]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [99]:
#splitting
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [100]:
#MLP 
model = Sequential()
#input layer
model.add(Dense(10,activation="relu",input_shape=[X_train.shape[1]]))
#middle layer
model.add(Dense(10,activation="relu"))
#output layer
model.add(Dense(1))

In [101]:
#model summary
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 10)                310       
                                                                 
 dense_16 (Dense)            (None, 10)                110       
                                                                 
 dense_17 (Dense)            (None, 1)                 11        
                                                                 
Total params: 431
Trainable params: 431
Non-trainable params: 0
_________________________________________________________________
None


In [102]:
model.compile(optimizer="adam",loss="mean_squared_error",metrics=["mse"])
model.fit(X_train,y_train,batch_size=50,validation_split=0.2,epochs=100,verbose=1)

Epoch 1/100
7/7 [==============================] - 1s 40ms/step - loss: 304.9879 - mse: 304.9879 - val_loss: 277.7376 - val_mse: 277.7376
Epoch 2/100
7/7 [==============================] - 0s 12ms/step - loss: 224.1872 - mse: 224.1872 - val_loss: 227.3209 - val_mse: 227.3209
Epoch 3/100
7/7 [==============================] - 0s 15ms/step - loss: 123.4153 - mse: 123.4153 - val_loss: 208.6044 - val_mse: 208.6044
Epoch 4/100
7/7 [==============================] - 0s 11ms/step - loss: 127.0920 - mse: 127.0920 - val_loss: 164.6770 - val_mse: 164.6770
Epoch 5/100
7/7 [==============================] - 0s 12ms/step - loss: 97.0928 - mse: 97.0928 - val_loss: 145.4313 - val_mse: 145.4313
Epoch 6/100
7/7 [==============================] - 0s 13ms/step - loss: 83.0052 - mse: 83.0052 - val_loss: 111.3906 - val_mse: 111.3906
Epoch 7/100
7/7 [==============================] - 0s 9ms/step - loss: 63.1056 - mse: 63.1056 - val_loss: 98.4010 - val_mse: 98.4010
Epoch 8/100
7/7 [==========================

In [103]:
results = model.evaluate(X_test,y_test)

6/6 [==============================] - 0s 2ms/step - loss: 0.8214 - mse: 0.8214


In [104]:
print(f"loss : {results[0]}")
print(f"accuracy : {results[1]}")

loss : 0.8213662505149841
accuracy : 0.8213662505149841
