simple example with two inputs and one output and logic AND

In [41]:
from numpy import exp, array, random, dot

In [42]:
#parameters
inputs = array([[0,0],[0,1],[1,0],[1,1]])
outputs = array([[0,1,1,1]]).T

In [43]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [44]:
outputs

array([[0],
       [1],
       [1],
       [1]])

In [45]:
random.seed(1)

In [46]:
weights = 2 * random.random((2,1)) - 1
weights

array([[-0.16595599],
       [ 0.44064899]])

In [47]:
# single neuron
def neuron(inputs,weights):
    output = 1 /  (1 + exp(-(dot(inputs,weights))))
    return output

In [48]:
#train
for iteration in range(500000):
    output = 1 / (1 + exp(-(dot(inputs,weights))))
    weights += dot(inputs.T, (outputs - output) * output * (1 - output))

In [49]:
#test 
x = array([1,0])
print(neuron(x,weights))

[0.998998]
