In [34]:
from numpy import linalg 
import numpy as np

In [35]:
L=[1,2,3,4,3,5]
arr1=np.array(L)
arr1

array([1, 2, 3, 4, 3, 5])

In [36]:
LN=[[1,2,3],[2,2,12]]
arr2=np.array(LN)
arr2

array([[ 1,  2,  3],
       [ 2,  2, 12]])

In [37]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [38]:
arr2.shape

(2, 3)

In [39]:
arr1.shape

(6,)

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Manipulatioin and Cleaning

In [44]:
#import relavant libries
import pandas as pd
import numpy as np

In [45]:
#datasets importing
#csv
df=pd.read_csv("iris.csv")
#xlsx
df_xlsx=pd.read_excel("iris.xlsx", sheet_name="marks")
#excel file
ef=pd.ExcelFile("iris.xlsx")

In [46]:
#excel file sheets
ef.sheet_names

['iris', 'marks']

In [47]:
#loading specific excel sheet for the df variable
df_excel=ef.parse("iris")

In [48]:
#show first 5 row to me
df.head()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0  1001           5.1          3.5           1.4          0.2  setosa
1  1002           4.9          3.0           1.4          0.2  setosa
2  1003           4.7          3.2           1.3          0.2  setosa
3  1004           4.6          3.1           1.5          0.2  setosa
4  1005           5.0          3.6           1.4          0.2  setosa

In [49]:
#see how many row and columns
df.shape

(150, 6)

In [50]:
#see all columns
df.columns

Index(['Id', 'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')