In [494]:
from numpy import linalg 
import numpy as np

In [495]:
L=[1,2,3,4,3,5]
arr1=np.array(L)
arr1

array([1, 2, 3, 4, 3, 5])

In [496]:
LN=[[1,2,3],[2,2,12]]
arr2=np.array(LN)
arr2

array([[ 1,  2,  3],
       [ 2,  2, 12]])

In [497]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [498]:
arr2.shape

(2, 3)

In [499]:
arr1.shape

(6,)

In [500]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [501]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [502]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [503]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Manipulatioin and Cleaning

In [504]:
#import relavant libries
import pandas as pd
import numpy as np

In [505]:
#datasets importing
#csv
df=pd.read_csv("iris.csv")
#xlsx
df_xlsx=pd.read_excel("iris.xlsx", sheet_name="marks")
#excel file
ef=pd.ExcelFile("iris.xlsx")

In [506]:
#excel file sheets
ef.sheet_names

['iris', 'marks']

In [507]:
#loading specific excel sheet for the df variable
df_excel=ef.parse("iris")

In [508]:
#show first 5 row to me
df.head()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0  1001           5.1          3.5           1.4          0.2  setosa
1  1002           4.9          3.0           1.4          0.2  setosa
2  1003           4.7          3.2           1.3          0.2  setosa
3  1004           4.6          3.1           1.5          0.2  setosa
4  1005           5.0          3.6           1.4          0.2  setosa

In [509]:
#see how many row and columns
df.shape

(150, 6)

In [510]:
#see all columns
df.columns

Index(['Id', 'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [511]:
#access column
df["Sepal.Width"]

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: Sepal.Width, Length: 150, dtype: float64

In [512]:
df[["Sepal.Width","Petal.Width"]]

Sepal.Width  Petal.Width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
..           ...          ...
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [513]:
#acces element
df["Sepal.Width"][0]

3.5

In [514]:
#df.iloc[rows,columns]
df.iloc[0,2]

3.5

In [515]:
df.iloc[1:4,1:4]

Sepal.Length  Sepal.Width  Petal.Length
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5

In [516]:
#using index
df.loc[1]

Id                1002
Sepal.Length       4.9
Sepal.Width          3
Petal.Length       1.4
Petal.Width        0.2
Species         setosa
Name: 1, dtype: object

In [517]:
#specific element
df.at[1,"Sepal.Length"]

4.9

In [518]:
df["Species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [519]:
#adding column with logic
df["target"]=[1 if s=="setosa" else 2 if s=="versicolor" else 3 for s in df["Species"]]

In [520]:
df.head()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  target
0  1001           5.1          3.5           1.4          0.2  setosa       1
1  1002           4.9          3.0           1.4          0.2  setosa       1
2  1003           4.7          3.2           1.3          0.2  setosa       1
3  1004           4.6          3.1           1.5          0.2  setosa       1
4  1005           5.0          3.6           1.4          0.2  setosa       1

In [521]:
#apply - appling functions in df
data=np.arange(30).reshape(10,3)
df1=pd.DataFrame(data,columns=["col1","col2","col3"])

In [522]:
df1

col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8
3     9    10    11
4    12    13    14
5    15    16    17
6    18    19    20
7    21    22    23
8    24    25    26
9    27    28    29

In [523]:
#axis=0 (column), axis=1 (row)
#default axis=0 
df1.apply(sum,axis=1)

0     3
1    12
2    21
3    30
4    39
5    48
6    57
7    66
8    75
9    84
dtype: int64

In [524]:
df1.apply(sum,axis=0)

col1    135
col2    145
col3    155
dtype: int64

In [525]:
fun =lambda L:L[0]+L[len(L)-1]
fun([1,23,3,4])

5

In [526]:
df1.apply(fun)

col1    27
col2    29
col3    31
dtype: int64

In [527]:
df1.apply(fun,axis=1)

0     2
1     8
2    14
3    20
4    26
5    32
6    38
7    44
8    50
9    56
dtype: int64

In [528]:
#boolean masking
df1["masking"]=df1["col3"]>10

In [529]:
df1

col1  col2  col3  masking
0     0     1     2    False
1     3     4     5    False
2     6     7     8    False
3     9    10    11     True
4    12    13    14     True
5    15    16    17     True
6    18    19    20     True
7    21    22    23     True
8    24    25    26     True
9    27    28    29     True

In [530]:
fun=lambda arr:(arr/sum(arr))*100

In [531]:
df1.apply(fun)

col1       col2       col3    masking
0   0.000000   0.689655   1.290323   0.000000
1   2.222222   2.758621   3.225806   0.000000
2   4.444444   4.827586   5.161290   0.000000
3   6.666667   6.896552   7.096774  14.285714
4   8.888889   8.965517   9.032258  14.285714
5  11.111111  11.034483  10.967742  14.285714
6  13.333333  13.103448  12.903226  14.285714
7  15.555556  15.172414  14.838710  14.285714
8  17.777778  17.241379  16.774194  14.285714
9  20.000000  19.310345  18.709677  14.285714

In [532]:
fun(df1["col1"])

0     0.000000
1     2.222222
2     4.444444
3     6.666667
4     8.888889
5    11.111111
6    13.333333
7    15.555556
8    17.777778
9    20.000000
Name: col1, dtype: float64

In [533]:
df1

col1  col2  col3  masking
0     0     1     2    False
1     3     4     5    False
2     6     7     8    False
3     9    10    11     True
4    12    13    14     True
5    15    16    17     True
6    18    19    20     True
7    21    22    23     True
8    24    25    26     True
9    27    28    29     True