In [62]:
from numpy import linalg 
import numpy as np

In [63]:
L=[1,2,3,4,3,5]
arr1=np.array(L)
arr1

array([1, 2, 3, 4, 3, 5])

In [64]:
LN=[[1,2,3],[2,2,12]]
arr2=np.array(LN)
arr2

array([[ 1,  2,  3],
       [ 2,  2, 12]])

In [65]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [66]:
arr2.shape

(2, 3)

In [67]:
arr1.shape

(6,)

In [68]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [71]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Manipulatioin and Cleaning

In [72]:
#import relavant libries
import pandas as pd
import numpy as np

In [73]:
#datasets importing
#csv
df=pd.read_csv("iris.csv")
#xlsx
df_xlsx=pd.read_excel("iris.xlsx", sheet_name="marks")
#excel file
ef=pd.ExcelFile("iris.xlsx")

In [74]:
#excel file sheets
ef.sheet_names

['iris', 'marks']

In [75]:
#loading specific excel sheet for the df variable
df_excel=ef.parse("iris")

In [76]:
#show first 5 row to me
df.head()

Id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0  1001           5.1          3.5           1.4          0.2  setosa
1  1002           4.9          3.0           1.4          0.2  setosa
2  1003           4.7          3.2           1.3          0.2  setosa
3  1004           4.6          3.1           1.5          0.2  setosa
4  1005           5.0          3.6           1.4          0.2  setosa

In [77]:
#see how many row and columns
df.shape

(150, 6)

In [78]:
#see all columns
df.columns

Index(['Id', 'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [79]:
#access column
df["Sepal.Width"]

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: Sepal.Width, Length: 150, dtype: float64

In [80]:
df[["Sepal.Width","Petal.Width"]]

Sepal.Width  Petal.Width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
..           ...          ...
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [81]:
#acces element
df["Sepal.Width"][0]

3.5

In [86]:
#df.iloc[rows,columns]
df.iloc[0,2]

3.5

In [88]:
df.iloc[1:4,1:4]

Sepal.Length  Sepal.Width  Petal.Length
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5